DATA:

  data_root: /root/ZengXiangyu/AESINetData
#  train_list: /root/ZengXiangyu/AESINetData/ORSSD4800train_list.txt
  train_list: /root/ZengXiangyu/AESINetData/EORSSD11200train_list.txt
#  train_list: /root/ZengXiangyu/AESINetData/ORSI16000train_list.txt



TRAIN:

  split: train  # split in [train, val and test]
  LR: 0.0001
  img_h: 224 
  img_w: 224 
  train_batch_size: 20
  epoch_num: 60


  block_num: 8  
  block_nod: 1 
  knn: 32
  img_dim: 32 
  cov_loop: 3 
  cov_bias: True 
  val_batch_size: 1  # batch size for validation during training, memory and speed tradeoff
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -90 #-10  # minimum random rotate
  rotate_max: 90 #10  # maximum random rotate
  ignore_label: 0 # 255
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  workers: 4  # data loader workers
  model_path: ./modelPTH/



TEST:

  split: test  # split in [train, val and test]
  test_h: 224
  test_w: 224
  test_batch_size: 8

#  test_list: /root/ZengXiangyu/AESINetData/ORSSDtest_list.txt
  test_list: /root/ZengXiangyu/AESINetData/EORSSDtest_list.txt
#  test_list: /root/ZengXiangyu/AESINetData/ORSItest_list.txt

#  results_folder: ./results/ORSSD/  # results save folder
  results_folder: ./results/EORSSD/  # results save folder
#  results_folder: ./results/ORSI/  # results save folder


  base_size: 224  # based size for scaling 
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  gpu: [3]







