DATA:
  data_root: /root/ILearnWork/ilData
#  train_list: F:/WORKs_SDU/datasets/DUTS-TR_list_Tiny.txt
#  train_list: F:/WORKs_SDU/datasets/DUTS-TR_list.txt
#  train_list: F:/WORKs_SDU/datasets/EORSSD-TR_list.txt
#  train_list: F:/WORKs_SDU/datasets/ORSSD-TR_list.txt
  train_list: /root/ILearnWork/ilData/ORSSD4800train_list.txt
#  train_list: F:/WORKs_SDU/datasets/EORSSD_train11200_list.txt
#  train_list: F:/WORKs_SDU/datasets/ORS-4199-TR_list.txt
#  train_list: F:/WORKs_SDU/datasets/bear_list.txt
TRAIN:
  split: train  # split in [train, val and test]
  # 块大小必须整除宽和高
  block_num: 8  # 长和宽方向上的分割数
  block_nod: 1 # 每个图块的节点数
  img_h: 224 #224 #256 #320
  img_w: 224 #224 #256 #320
  knn: 32
  img_dim: 32 # 图像维度
  cov_loop: 3 # 卷积总层数
  cov_bias: True # 单层卷积是否加偏置

  train_batch_size: 8 #14
  val_batch_size: 1  # batch size for validation during training, memory and speed tradeoff
  epoch_num: 40

  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -90 #-10  # minimum random rotate
  rotate_max: 90 #10  # maximum random rotate
  ignore_label: 0 # 255
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]

  workers: 4  # data loader workers

  model_path: ./modelPTH/


TEST:
#  test_list: /raid/workspace/loc_toy/dataset/cod/COD10K_test/test.lst
  test_list: /root/ILearnWork/ilData/EORSSDtest_list.txt
#  test_list: F:/WORKs_SDU/datasets/ORS-4199-TE_list.txt
#  test_list: F:/WORKs_SDU/datasets/EORSSD-TE_list.txt
  split: test  # split in [train, val and test]
  base_size: 224  # based size for scaling 
  test_h: 224
  test_w: 224
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  test_batch_size: 4
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  gpu: [3]
#  model_path:  model_file/mgl_r.pth
  results_folder: ./results/EORSSD-TE/  # results save folder
#  results_folder: ./results/ORS-4199-TE/  # results save folder
#  results_folder: ./results/EORSSD-TE/  # results save folder
